In [1]:
import pandas as pd
df_data = pd.read_csv(r"/home/devesh/Documents/edwisor_assignment/data.csv", encoding = "unicode_escape", skiprows = [2], thousands=',')

In [2]:
df_data

,Plot,Title,imdbVotes,Poster,imdbRating,Genre,imdbID,Year,Language
0,Despite his tarnished reputation after the eve...,The Dark Knight Rises,2679,http://ia.media-imdb.com/images/M/MV5BMTk4ODQz...,75,"Action, Thriller",tt1345836,2012,English
1,"Based on the novel written by Stephen Chbosky,...",The Perks of Being a Wallflower,1270,http://ia.media-imdb.com/images/M/MV5BMzIxOTQy...,71,"Drama, Romance",tt1659337,2012,English
2,Mike Lane is a thirty-year old living in Tampa...,Magic Mike,2580,http://ia.media-imdb.com/images/M/MV5BMTQzMDMz...,51,"Comedy, Drama",tt1915581,2012,English
3,When Bond's latest assignment goes gravely wro...,Skyfall,1807,http://ia.media-imdb.com/images/M/MV5BMjAyODkz...,68,"Action, Thriller",tt1074638,2012,English
4,Against medical advice and without the knowled...,Silver Linings Playbook,1828,http://ia.media-imdb.com/images/M/MV5BMTM2MTI5...,68,"Comedy, Drama, Romance",tt1045658,2012,English
5,A shy senior and a down-to-earth junior fall i...,The First Time,1538,http://ia.media-imdb.com/images/M/MV5BMjMxNDI1...,60,"Comedy, Drama, Romance",tt1763303,2012,English
6,"In California, the former Navy SEAL Chon and h...",Savages,2683,http://ia.media-imdb.com/images/M/MV5BMTk0ODIy...,55,"Crime, Drama, Thriller",tt1615065,2012,English
7,Meet the Borgens. William Borgens is an acclai...,Stuck in Love,1832,http://ia.media-imdb.com/images/M/MV5BMTU1NzI5...,63,"Comedy, Drama, Romance",tt2205697,2012,English
8,"In 1874, in the Imperial Russia, the aristocra...",Anna Karenina,2094,http://ia.media-imdb.com/images/M/MV5BMTU0NDgx...,56,"Drama, Romance",tt1781769,2012,English
9,"In the 1960s, Richard Kuklinski is working as ...",The Iceman,1859,http://ia.media-imdb.com/images/M/MV5BNDQyMjM5...,59,"Biography, Crime, Drama",tt1491044,2012,English
10,The sunrise blinds the early risers of the cit...,Broken Ledge,2718,http://ia.media-imdb.com/images/M/MV5BMTcyMzYz...,87,Drama,tt2508268,2012,English
11,A mysterious traveler infiltrates a dangerous ...,In the Realms of Madness,2718,http://ia.media-imdb.com/images/M/MV5BNzA2NzE3...,87,"Drama, Horror",tt2248841,2012,English
12,"In both its story on and off the screen, 'Flan...",Flaneurs,2718,NaN,87,"Drama, Romance",tt2364671,2012,English
13,Hailey is in an unhappy marriage but she devel...,The Start of Something Good,2718,NaN,87,"Drama, Romance",tt2331062,2012,English
14,Yannick has to deal with the haunting by himse...,True Storys of the Ghost House 3 the Demon Phe...,2718,NaN,87,Horror,tt3098520,2012,English
15,Seduced by the haunting beauty of a remote mar...,White Wind,2718,NaN,87,"Drama, Mystery",tt2555620,2012,English
16,A psychotic Iraq War veteran teaches his young...,Thelema the Equinox Diaries,2718,NaN,87,"Drama, Thriller",tt2443106,2012,English
17,A politician receives a message that his mistr...,Home Minister,2718,NaN,87,Drama,tt2923826,2012,English
18,A plot to assassinate the Vice President takes...,Placebo Effect,1752,http://ia.media-imdb.com/images/M/MV5BMTU5Njg1...,52,"Crime, Mystery, Thriller",tt0163154,1998,English
19,Long on the Island is a psychological thriller...,Long on the Island,2718,NaN,87,"Fantasy, Horror",tt2375263,2012,English
20,"Over the course of a single night, Dave and An...",I Did,2718,NaN,87,"Drama, Family",tt2388672,2012,English
21,"""Collaging Film"" is a series of shorts dating ...",Collaging Film,2718,NaN,87,Animation,tt4416372,2012,English
22,Hank lives the quiet life until a mysterious i...,Welcoming Departure,2718,http://ia.media-imdb.com/images/M/MV5BMjE0OTU2...,87,"Comedy, Drama",tt2235809,2012,English
23,The Luckiest Girl on the Lower East Side takes...,The Luckiest Girl on the Lower East Side,2718,NaN,87,Drama,tt1876494,2012,English
24,"Less Lost, is the fictional story of a young m...",Less Lost,1114,http://ia.media-imdb.com/images/M/MV5BMTk3MTg2...,68,"Drama, War",tt2259946,2012,English
25,High school student Aidan loses his girlfriend...,Still Here,2302,NaN,53,Drama,tt2275650,2012,English
26,Best friends Sam and Mike go out on a bender a...,The Hedgehog Dilemma,2718,http://ia.media-imdb.com/images/M/MV5BMTU1NDI3...,87,"Drama, Romance",tt2505274,2012,English
27,Filmed and produced by Australian director Sha...,51 Paintings,2457,http://ia.media-imdb.com/images/M/MV5BMTQyNzU2...,61,Drama,tt2318982,2012,English
28,"Capitalists, revolutionaries, and the people w...",The Adventures of Paul and Marian,2718,NaN,87,"Comedy, Musical, Romance",tt1949593,2012,English
29,Various people who lost loved ones during 9-11...,Above the Fire,2718,http://ia.media-imdb.com/images/M/MV5BMTUzNzc5...,87,Drama,tt2231544,2012,English
...,...,...,...,...,...,...,...,...,...
3359,Prabhavati lives a wealthy lifestyle in India ...,Sneham Kosam,NaN,NaN,6.3,"Family, Action",tt0246240,1999,Telugu
3360,The story of the famous Saint-Poet Manjunatha.,Sri Manjunatha,NaN,NaN,6.7,"Drama, Family, History, Musical",tt0249783,2001,Telugu
3361,Lord Rama's life is one of perfect adherence t...,Sri Rama Rajyam,635,NaN,7.2,Drama,tt1783377,2011,Telugu
3362,Based on the life story of the great devotee-m...,Sri Ramadasu,207,NaN,6.9,"Biography, Musical",tt0459205,2006,Telugu
3363,Josef Stalin rises from his rejection as being...,Stalin,653,http://ia.media-imdb.com/images/M/MV5BMTk5OTQw...,5.6,"Action, Drama",tt0105462,2006,Telugu
3364,"The story of aspiring police officer, Prithvir...",State Rowdy,68,NaN,7.4,"Action, Crime, Drama",tt0246254,1989,Telugu
3365,Aditya lives a middle-classed lifestyle in Aur...,Student No 1,473,NaN,6.7,"Action, Crime, Drama",tt1283956,2001,Telugu
3366,Bantu and Chantu are two close friends and fel...,Style,NaN,NaN,5.8,Musical,tt0306855,2006,Telugu
3367,Amarchandra lives a poor lifestyle in British ...,Subhash Chandra Bose,NaN,NaN,2.9,"Action, Drama, History, Romance, Thriller",tt0459554,2005,Telugu
3368,Frank Darrbo is a hapless fry cook. When his w...,Super,NaN,http://ia.media-imdb.com/images/M/MV5BMTcxMDkx...,5.1,"Action, Comedy, Drama, Mystery, Romance",tt1512235,2005,Telugu
3369,Unable to convince the ruling council of Krypt...,Superman,49,http://ia.media-imdb.com/images/M/MV5BMTI1MjA5...,4.2,"Fantasy, Musical, Sci-Fi",tt0078346,1980,Telugu
3370,A priceless idol is stolen from a temple trave...,Swamy Ra Ra,443,NaN,7.5,Crime,tt2767354,2013,Telugu
3371,"The story of a classical singer, who finds it ...",Swathi Kiranam,NaN,NaN,7.8,"Family, Musical, Drama",tt0250012,1992,Telugu
3372,"Ravindranath Tagore, A physics professor forms...",Tagore,861,NaN,7.6,"Action, Drama",tt0361037,2003,Telugu
3373,"Raja is a small-time outlaw, whose daring anti...",Takkari Donga,644,NaN,6.9,"Action, Adventure, Western",tt0307541,2002,Telugu
3374,The story of an Indian Freedom fighter who fou...,Tandra Paparayudu,61,NaN,8,"Action, Biography, Drama, History",tt0253784,1986,Telugu
3375,"Raghu, a business tycoon, is driving through a...",Tarzan Sundari,7,NaN,6,"Action, Adventure, Fantasy, Musical",tt2735328,1983,Telugu
3376,A man reconsiders his ideas about love in the ...,Teen Maar,909,NaN,5.8,"Comedy, Drama, Romance",tt1889440,2011,Telugu
3377,Daya (NTR) is a fully corrupted police officer...,Temper,"1,331",NaN,8.1,"Action, Drama",tt4442758,2015,Telugu
3378,Classic about the life story of Carnatic Music...,Thyagayya,NaN,NaN,7.3,"Family, History, Musical",tt0246277,1946,Telugu
3379,"A romantic entertainer between a ""bava"" and a ...",Uyyala Jampala,NaN,NaN,7.5,"Drama, Family, Romance",tt3290676,2013,Telugu
3380,About to re-locate to the U.S. but refusing to...,Varudu,438,NaN,3.5,"Action, Crime, Drama, Thriller",tt1582637,2010,Telugu
3381,Cable Raju is a slum dweller who works as a ca...,Vedam,"2,015",NaN,8.1,Drama,tt1649431,2010,Telugu
3382,A simple train journey to Tirupathi goes horri...,Venkatadri Express,79,NaN,7.5,"Adventure, Comedy",tt3573040,2013,Telugu
3383,Venky and his friends are accused of murdering...,Venky,NaN,NaN,7.1,"Mystery, Romance",tt0417229,2004,Telugu
3384,"Vikram Rathod, A sincere Police man joins with...",Vikramarkudu,"1,158",NaN,7.5,"Action, Comedy, Crime, Thriller",tt0858492,2006,Telugu
3385,After an eventful train trip on the Visakha/Ra...,Visakha Express,43,NaN,4.5,"Crime, Drama, Mystery, Thriller",tt1285147,2008,Telugu
3386,"Mahi is a beautiful wealthy heiress, but her f...",Yamadonga,"1,316",NaN,7.3,"Action, Comedy, Fantasy, Romance",tt0924317,2007,Telugu
3387,Yevade Subramanyam has wrapped its shooting an...,Yevade Subramanyam,188,NaN,7.9,"Adventure, Comedy, Drama",tt4515070,2015,Telugu
3388,Sathya (Allu Arjun) returns from a coma to tak...,Yevadu,"3,966",NaN,4.6,"Action, Thriller",tt2211173,2014,Telugu

In [4]:
df_data.shape

(3389, 9)

In [5]:
df_geners_action = df_data.loc[(df_data['Genre'] == "Action")]

In [6]:
df_geners_action.shape

(41, 9)

In [7]:
df_genre_romance = df_data.loc[(df_data['Genre'].str.contains("Romance"))]

In [8]:
df_genre_romance.shape

(589, 9)

In [9]:
df_data.count(axis = 0)

Plot          3389
Title         3389
imdbVotes     3334
Poster        1836
imdbRating    3388
Genre         3389
imdbID        3389
Year          3389
Language      3389
dtype: int64

In [10]:
b = []
a = [x.split(', ') for x in df_data.Genre.unique()]
a

[['Action', 'Thriller'],
 ['Drama', 'Romance'],
 ['Comedy', 'Drama'],
 ['Comedy', 'Drama', 'Romance'],
 ['Crime', 'Drama', 'Thriller'],
 ['Biography', 'Crime', 'Drama'],
 ['Drama'],
 ['Drama', 'Horror'],
 ['Horror'],
 ['Drama', 'Mystery'],
 ['Drama', 'Thriller'],
 ['Crime', 'Mystery', 'Thriller'],
 ['Fantasy', 'Horror'],
 ['Drama', 'Family'],
 ['Animation'],
 ['Drama', 'War'],
 ['Comedy', 'Musical', 'Romance'],
 ['Comedy', 'Drama', 'Family'],
 ['Action', 'Crime', 'Drama'],
 ['Action', 'Adventure', 'Drama'],
 ['Comedy'],
 ['Comedy', 'Crime'],
 ['Action', 'Comedy', 'Romance'],
 ['Action', 'Comedy'],
 ['Crime'],
 ['Fantasy'],
 ['Action', 'Drama'],
 ['Comedy', 'Romance'],
 ['Adventure', 'Comedy', 'Drama'],
 ['Crime', 'Drama'],
 ['Drama', 'History'],
 ['Drama', 'Fantasy', 'Romance'],
 ['Drama', 'Fantasy'],
 ['Drama', 'Mystery', 'Thriller'],
 ['Action', 'Fantasy'],
 ['Drama', 'Thriller', 'War'],
 ['Drama', 'Sport'],
 ['Action'],
 ['Sci-Fi'],
 ['Mystery'],
 ['Comedy', 'Drama', 'Fantasy'],
 ['Action', 'Drama', 'Romance'],
 ['Crime', 'Thriller'],
 ['Comedy', 'Sport'],
 ['Action', 'Horror'],
 ['Comedy', 'Family'],
 ['Action', 'Comedy', 'Drama'],
 ['Mystery', 'Thriller'],
 ['Horror', 'Thriller'],
 ['Biography', 'Comedy', 'Drama'],
 ['Comedy', 'Horror', 'Thriller'],
 ['Action', 'Drama', 'Family'],
 ['Drama', 'Family', 'Thriller'],
 ['Horror', 'Mystery', 'Thriller'],
 ['Family'],
 ['Biography', 'Drama', 'Sport'],
 ['Adventure', 'Comedy', 'Crime'],
 ['Drama', 'Music'],
 ['Adventure', 'Drama', 'Fantasy'],
 ['Musical'],
 ['Adventure'],
 ['Drama', 'Mystery', 'Romance'],
 ['Drama', 'Fantasy', 'Thriller'],
 ['Drama', 'Family', 'Romance'],
 ['Comedy', 'Family', 'Romance'],
 ['Drama', 'History', 'War'],
 ['Comedy', 'Crime', 'Drama'],
 ['Comedy', 'Mystery', 'Thriller'],
 ['Adventure', 'Drama'],
 ['Comedy', 'Mystery'],
 ['Action', 'Crime', 'Thriller'],
 ['Drama', 'Musical', 'Romance'],
 ['Action', 'Crime'],
 ['Drama', 'Romance', 'Thriller'],
 ['Biography', 'Drama', 'History'],
 ['Drama', 'Family', 'Sport'],
 ['Comedy', 'Crime', 'Thriller'],
 ['Sport'],
 ['Adventure', 'Thriller'],
 ['Crime', 'Drama', 'Romance'],
 ['Action', 'Adventure'],
 ['Fantasy', 'Romance'],
 ['History'],
 ['Adventure', 'Drama', 'Romance'],
 ['Adventure', 'Family', 'Fantasy'],
 ['Adventure', 'Comedy'],
 ['Comedy', 'Mystery', 'Romance'],
 ['Action', 'Adventure', 'Thriller'],
 ['Action', 'Drama', 'War'],
 ['Crime', 'Horror', 'Thriller'],
 ['Drama', 'Family', 'Music'],
 ['Action', 'Crime', 'Romance'],
 ['Music', 'Musical'],
 ['Comedy', 'Drama', 'Sport'],
 ['Comedy', 'Romance', 'Thriller'],
 ['Horror', 'Romance', 'Thriller'],
 ['Action', 'Romance'],
 ['Family', 'Musical', 'Romance'],
 ['Mystery', 'Romance'],
 ['Action', 'Adventure', 'Western'],
 ['Family', 'Musical'],
 ['Action', 'Comedy', 'Family'],
 ['Action', 'Romance', 'Thriller'],
 ['Drama', 'Horror', 'Mystery', 'Romance', 'Thriller'],
 ['Crime', 'Drama', 'Mystery', 'Sci-Fi', 'Thriller'],
 ['Crime', 'Drama', 'Mystery', 'Thriller'],
 ['Drama', 'Music', 'Musical', 'Romance'],
 ['Drama', 'Musical', 'Family'],
 ['Thriller', 'Mystery'],
 ['Action', 'Comedy', 'Drama', 'Musical'],
 ['Action', 'Comedy', 'Drama', 'Family'],
 ['Comedy', 'Drama', 'Musical', 'Romance'],
 ['Action', 'Drama', 'History', 'Romance', 'War'],
 ['Action', 'Comedy', 'Musical', 'Thriller'],
 ['Action', 'Crime', 'Drama', 'Thriller'],
 ['Action', 'Adventure', 'Comedy', 'Romance', 'Thriller'],
 ['Adventure', 'Comedy', 'Drama', 'Romance'],
 ['Comedy', 'Musical', 'Drama', 'Family'],
 ['Drama', 'Family', 'Musical', 'Romance'],
 ['Biography', 'Drama', 'History', 'Sport'],
 ['Comedy', 'Horror', 'Mystery', 'Thriller'],
 ['Biography', 'Crime', 'Drama', 'History', 'Thriller'],
 ['Action', 'War'],
 ['Comedy', 'Drama', 'Family', 'Romance'],
 ['Action', 'Crime', 'Thriller', 'Drama'],
 ['Drama', 'Action', 'Comedy', 'Romance', 'Family'],
 ['Action', 'Comedy', 'Crime', 'Romance', 'Thriller'],
 ['Action', 'Comedy', 'Drama', 'Musical', 'Romance'],
 ['Horror', 'Adventure'],
 ['Drama', 'Mystery', 'Romance', 'Thriller'],
 ['Action', 'Comedy', 'Crime', 'Musical', 'Romance'],
 ['Musical', 'Romance'],
 ['Musical', 'Drama', 'Adventure', 'Comedy'],
 ['Drama', 'Romance', 'Musical', 'Thriller'],
 ['Comedy', 'Musical', 'Drama', 'Romance'],
 ['Action', 'Crime', 'Drama', 'Mystery', 'Thriller'],
 ['Adventure', 'Crime', 'Drama', 'Romance', 'Thriller'],
 ['Drama', 'Romance', 'War'],
 ['Action', 'Adventure', 'Crime', 'Drama', 'Thriller'],
 ['Adventure', 'Comedy', 'Crime', 'Drama'],
 ['Crime', 'Drama', 'Mystery', 'Romance', 'Thriller'],
 ['Action', 'Drama', 'Mystery', 'Romance', 'Thriller'],
 ['Action', 'Adventure', 'Comedy', 'Horror'],
 ['Biography', 'Drama', 'Musical', 'Romance'],
 ['Crime', 'Drama', 'Romance', 'Thriller'],
 ['Family', 'Comedy', 'Drama', 'Romance'],
 ['Action', 'Comedy', 'Crime', 'Drama', 'Musical', 'Romance'],
 ['Action', 'Adventure', 'Comedy', 'Crime', 'Musical'],
 ['Action', 'Crime', 'Drama', 'Family'],
 ['Drama', 'Family', 'Comedy', 'Romance'],
 ['Musical', 'Drama', 'Family'],
 ['Drama', 'Romance', 'Comedy', 'Musical'],
 ['Action', 'Musical', 'Mystery', 'Drama', 'Thriller', 'Romance'],
 ['Action',
  'Adventure',
  'Biography',
  'Drama',
  'History',
  'Musical',
  'Romance'],
 ['Action', 'Drama', 'Musical', 'Romance'],
 ['Comedy', 'Drama', 'Music', 'Romance'],
 ['Action', 'Crime', 'Drama', 'Mystery', 'Romance', 'Thriller'],
 ['Action', 'Comedy', 'Crime', 'Drama', 'Thriller'],
 ['Action', 'Comedy', 'Fantasy', 'Romance'],
 ['Action', 'Comedy', 'Romance', 'Thriller'],
 ['Drama', 'Fantasy', 'Romance', 'Sci-Fi'],
 ['Action', 'Drama', 'Musical', 'Romance', 'Thriller'],
 ['Action', 'Adventure', 'Romance', 'Sci-Fi'],
 ['Romance', 'Sci-Fi'],
 ['Family', 'Musical', 'Drama', 'Romance'],
 ['Adventure', 'Drama', 'Musical', 'Romance', 'Sport'],
 ['War', 'Drama', 'Romance'],
 ['Action', 'Drama', 'History', 'Thriller', 'War'],
 ['Drama', 'Family', 'Musical'],
 ['Comedy', 'Crime', 'Mystery', 'Romance', 'Thriller'],
 ['Musical', 'Drama', 'Romance'],
 ['Action',
  'Adventure',
  'Comedy',
  'Drama',
  'Fantasy',
  'Musical',
  'Romance',
  'Sci-Fi'],
 ['Action', 'Comedy', 'Drama', 'Fantasy'],
 ['Musical', 'Romance', 'Drama', 'Family'],
 ['Drama', 'Fantasy', 'Mystery', 'Thriller'],
 ['Action', 'Comedy', 'Drama', 'Musical', 'Romance', 'Thriller'],
 ['Comedy', 'Drama', 'Family', 'Fantasy'],
 ['Action', 'Crime', 'Drama', 'Romance', 'Thriller'],
 ['Action', 'Biography', 'Crime', 'Sport', 'Thriller'],
 ['Musical', 'Romance', 'Action', 'Drama'],
 ['Comedy', 'Drama', 'Mystery', 'Romance', 'Sci-Fi'],
 ['Drama', 'Horror', 'Mystery', 'Thriller'],
 ['Drama', 'Romance', 'Musical', 'Comedy', 'Action'],
 ['Musical', 'Comedy', 'Romance'],
 ['Action', 'Biography', 'Crime', 'Drama', 'Thriller'],
 ['Action', 'Drama', 'Family', 'Musical'],
 ['Comedy', 'Drama', 'History', 'Music', 'Romance'],
 ['Adventure', 'Musical', 'Romance'],
 ['Drama', 'Romance', 'Musical', 'Comedy'],
 ['Fantasy', 'Horror', 'Musical', 'Mystery', 'Romance', 'Thriller'],
 ['Biography', 'Crime', 'Drama', 'Thriller'],
 ['Action', 'Adventure', 'Crime', 'Drama', 'Family'],
 ['Action', 'Comedy', 'Family', 'Romance'],
 ['Action', 'Adventure', 'Comedy', 'Drama', 'Musical', 'Thriller'],
 ['Action', 'Comedy', 'Crime', 'Romance'],
 ['Action', 'Drama', 'Musical', 'Mystery', 'Romance', 'Thriller'],
 ['Crime', 'Drama', 'History', 'Thriller'],
 ['Action', 'Adventure', 'Drama', 'Thriller'],
 ['Biography', 'Drama', 'History', 'War'],
 ['Action', 'Drama', 'Mystery', 'Thriller'],
 ['Drama', 'Romance', 'Action', 'Musical', 'Family'],
 ['Action', 'Adventure', 'Crime', 'Drama'],
 ['Adventure', 'Comedy', 'Drama', 'Family', 'Romance'],
 ['Biography', 'Drama', 'History', 'Musical', 'Romance'],
 ['Family', 'Sci-Fi', 'Adventure', 'Comedy'],
 ['Drama', 'History', 'Musical'],
 ['Action', 'Adventure', 'Drama', 'Sci-Fi', 'Thriller'],
 ['History', 'Musical'],
 ['Action', 'Comedy', 'Musical', 'Romance', 'Thriller'],
 ['Action', 'Crime', 'Drama', 'Romance'],
 ['Musical', 'Mystery', 'Thriller'],
 ['Comedy', 'Family', 'Drama'],
 ['Action', 'Comedy', 'Crime', 'Thriller'],
 ['Action', 'Adventure', 'Drama', 'Fantasy'],
 ['Action', 'Drama', 'Crime', 'Thriller'],
 ['Action', 'Drama', 'History', 'War'],
 ['Action', 'Comedy', 'Crime', 'Drama'],
 ['Action', 'Adventure', 'Fantasy', 'Horror', 'Thriller'],
 ['Action', 'Crime', 'Drama', 'Mystery', 'Romance'],
 ['Family', 'Comedy', 'Drama', 'Fantasy'],
 ['Action', 'Comedy', 'Romance', 'Sport'],
 ['Drama', 'Comedy', 'Family', 'Romance'],
 ['Action', 'Musical'],
 ['Comedy', 'Crime', 'Drama', 'Thriller'],
 ['Musical', 'Drama', 'Action', 'War'],
 ['Family', 'Musical', 'Comedy', 'Drama'],
 ['Comedy', 'Drama', 'Family', 'Musical'],
 ['Crime', 'Drama', 'Family', 'Thriller'],
 ['Action', 'Crime', 'Romance', 'Thriller'],
 ['Biography', 'Drama', 'Family', 'History'],
 ['Action', 'Adventure', 'Comedy', 'Drama'],
 ['Action', 'Drama', 'Mystery', 'Romance'],
 ['Action', 'Comedy', 'Drama', 'Romance'],
 ['Action', 'Drama', 'History', 'Musical'],
 ['Action', 'Biography', 'History'],
 ['Musical', 'Romance', 'Drama'],
 ['Drama', 'Family', 'Fantasy', 'History'],
 ['Adventure', 'Comedy', 'Crime', 'Thriller'],
 ['Musical', 'Drama'],
 ['Family', 'Action'],
 ['Drama', 'Family', 'History', 'Musical'],
 ['Biography', 'Musical'],
 ['Action', 'Drama', 'History', 'Romance', 'Thriller'],
 ['Action', 'Comedy', 'Drama', 'Mystery', 'Romance'],
 ['Fantasy', 'Musical', 'Sci-Fi'],
 ['Family', 'Musical', 'Drama'],
 ['Action', 'Biography', 'Drama', 'History'],
 ['Action', 'Adventure', 'Fantasy', 'Musical'],
 ['Family', 'History', 'Musical']]

In [11]:
a = {}
for index, row in df_data.iterrows(): 
    genres = row['Genre'].split(', ')
    for genre in  genres:
        if genre not in a:
            a[genre] = 0
        a[genre] += 1

In [12]:
print(a.keys())

dict_keys(['Action', 'Thriller', 'Drama', 'Romance', 'Comedy', 'Crime', 'Biography', 'Horror', 'Mystery', 'Fantasy', 'Family', 'Animation', 'War', 'Musical', 'Adventure', 'History', 'Sport', 'Sci-Fi', 'Music', 'Western'])

In [13]:
genre_list = []
for key, value in a.items():
    genre_list.append({'genre':key, 'count': value})
print(genre_list)

[{'genre': 'Action', 'count': 355}, {'genre': 'Thriller', 'count': 510}, {'genre': 'Drama', 'count': 2169}, {'genre': 'Romance', 'count': 589}, {'genre': 'Comedy', 'count': 1246}, {'genre': 'Crime', 'count': 364}, {'genre': 'Biography', 'count': 53}, {'genre': 'Horror', 'count': 259}, {'genre': 'Mystery', 'count': 224}, {'genre': 'Fantasy', 'count': 99}, {'genre': 'Family', 'count': 245}, {'genre': 'Animation', 'count': 13}, {'genre': 'War', 'count': 31}, {'genre': 'Musical', 'count': 125}, {'genre': 'Adventure', 'count': 128}, {'genre': 'History', 'count': 62}, {'genre': 'Sport', 'count': 57}, {'genre': 'Sci-Fi', 'count': 40}, {'genre': 'Music', 'count': 31}, {'genre': 'Western', 'count': 2}]

In [14]:
df_genre = pd.DataFrame(genre_list).set_index('genre')

In [15]:
df_genre

           count
genre
Action       355
Thriller     510
Drama       2169
Romance      589
Comedy      1246
Crime        364
Biography     53
Horror       259
Mystery      224
Fantasy       99
Family       245
Animation     13
War           31
Musical      125
Adventure    128
History       62
Sport         57
Sci-Fi        40
Music         31
Western        2

In [16]:
df_genre = df_genre.sort_values('genre', ascending = True)

In [17]:
df_genre

           count
genre
Action       355
Adventure    128
Animation     13
Biography     53
Comedy      1246
Crime        364
Drama       2169
Family       245
Fantasy       99
History       62
Horror       259
Music         31
Musical      125
Mystery      224
Romance      589
Sci-Fi        40
Sport         57
Thriller     510
War           31
Western        2

In [18]:
df_data = df_data.astype(object)

In [19]:
df_data["imdbVotes"] = df_data["imdbVotes"].str.replace(',', '')
df_data["imdbVotes"] = df_data["imdbVotes"].str.replace('-', '')
df_data['imdbVotes'].fillna('0')
df_data["imdbVotes"] = pd.to_numeric(df_data["imdbVotes"])

In [20]:
df_data["imdbRating"] = df_data["imdbRating"].str.replace('-', '')
df_data['imdbRating'].fillna('0')

df_data["imdbRating"] = pd.to_numeric(df_data['imdbRating']).astype(float)
df_data["imdbRating"]

0       75.0
1       71.0
2       51.0
3       68.0
4       68.0
5       60.0
6       55.0
7       63.0
8       56.0
9       59.0
10      87.0
11      87.0
12      87.0
13      87.0
14      87.0
15      87.0
16      87.0
17      87.0
18      52.0
19      87.0
20      87.0
21      87.0
22      87.0
23      87.0
24      68.0
25      53.0
26      87.0
27      61.0
28      87.0
29      87.0
        ...
3359     6.3
3360     6.7
3361     7.2
3362     6.9
3363     5.6
3364     7.4
3365     6.7
3366     5.8
3367     2.9
3368     5.1
3369     4.2
3370     7.5
3371     7.8
3372     7.6
3373     6.9
3374     8.0
3375     6.0
3376     5.8
3377     8.1
3378     7.3
3379     7.5
3380     3.5
3381     8.1
3382     7.5
3383     7.1
3384     7.5
3385     4.5
3386     7.3
3387     7.9
3388     4.6
Name: imdbRating, Length: 3389, dtype: float64

In [23]:
df_data['new_var'] = df_data['imdbVotes'] - df_data['imdbRating']

In [24]:
df_data['new_var'] = df_data['new_var'] * df_data['new_var']

In [25]:
df_data['new_var']

0        6780816.00
1        1437601.00
2        6395841.00
3        3024121.00
4        3097600.00
5        2184484.00
6        6906384.00
7        3129361.00
8        4153444.00
9        3240000.00
10       6922161.00
11       6922161.00
12       6922161.00
13       6922161.00
14       6922161.00
15       6922161.00
16       6922161.00
17       6922161.00
18       2890000.00
19       6922161.00
20       6922161.00
21       6922161.00
22       6922161.00
23       6922161.00
24       1094116.00
25       5058001.00
26       6922161.00
27       5740816.00
28       6922161.00
29       6922161.00
           ...
3359            NaN
3360            NaN
3361      394132.84
3362       40040.01
3363      419126.76
3364        3672.36
3365      217435.69
3366            NaN
3367            NaN
3368            NaN
3369        2007.04
3370      189660.25
3371            NaN
3372      728291.56
3373      405896.41
3374        2809.00
3375           1.00
3376      815770.24
3377     1750064.41
3378            NaN
3379            NaN
3380      188790.25
3381     4027647.61
3382        5112.25
3383            NaN
3384     1323650.25
3385        1482.25
3386     1712695.69
3387       32436.01
3388    15692689.96
Name: new_var, Length: 3389, dtype: float64

In [26]:
df_data

,Plot,Title,imdbVotes,Poster,imdbRating,Genre,imdbID,Year,Language,new_var
0,Despite his tarnished reputation after the eve...,The Dark Knight Rises,2679.0,http://ia.media-imdb.com/images/M/MV5BMTk4ODQz...,75.0,"Action, Thriller",tt1345836,2012,English,6780816.00
1,"Based on the novel written by Stephen Chbosky,...",The Perks of Being a Wallflower,1270.0,http://ia.media-imdb.com/images/M/MV5BMzIxOTQy...,71.0,"Drama, Romance",tt1659337,2012,English,1437601.00
2,Mike Lane is a thirty-year old living in Tampa...,Magic Mike,2580.0,http://ia.media-imdb.com/images/M/MV5BMTQzMDMz...,51.0,"Comedy, Drama",tt1915581,2012,English,6395841.00
3,When Bond's latest assignment goes gravely wro...,Skyfall,1807.0,http://ia.media-imdb.com/images/M/MV5BMjAyODkz...,68.0,"Action, Thriller",tt1074638,2012,English,3024121.00
4,Against medical advice and without the knowled...,Silver Linings Playbook,1828.0,http://ia.media-imdb.com/images/M/MV5BMTM2MTI5...,68.0,"Comedy, Drama, Romance",tt1045658,2012,English,3097600.00
5,A shy senior and a down-to-earth junior fall i...,The First Time,1538.0,http://ia.media-imdb.com/images/M/MV5BMjMxNDI1...,60.0,"Comedy, Drama, Romance",tt1763303,2012,English,2184484.00
6,"In California, the former Navy SEAL Chon and h...",Savages,2683.0,http://ia.media-imdb.com/images/M/MV5BMTk0ODIy...,55.0,"Crime, Drama, Thriller",tt1615065,2012,English,6906384.00
7,Meet the Borgens. William Borgens is an acclai...,Stuck in Love,1832.0,http://ia.media-imdb.com/images/M/MV5BMTU1NzI5...,63.0,"Comedy, Drama, Romance",tt2205697,2012,English,3129361.00
8,"In 1874, in the Imperial Russia, the aristocra...",Anna Karenina,2094.0,http://ia.media-imdb.com/images/M/MV5BMTU0NDgx...,56.0,"Drama, Romance",tt1781769,2012,English,4153444.00
9,"In the 1960s, Richard Kuklinski is working as ...",The Iceman,1859.0,http://ia.media-imdb.com/images/M/MV5BNDQyMjM5...,59.0,"Biography, Crime, Drama",tt1491044,2012,English,3240000.00
10,The sunrise blinds the early risers of the cit...,Broken Ledge,2718.0,http://ia.media-imdb.com/images/M/MV5BMTcyMzYz...,87.0,Drama,tt2508268,2012,English,6922161.00
11,A mysterious traveler infiltrates a dangerous ...,In the Realms of Madness,2718.0,http://ia.media-imdb.com/images/M/MV5BNzA2NzE3...,87.0,"Drama, Horror",tt2248841,2012,English,6922161.00
12,"In both its story on and off the screen, 'Flan...",Flaneurs,2718.0,NaN,87.0,"Drama, Romance",tt2364671,2012,English,6922161.00
13,Hailey is in an unhappy marriage but she devel...,The Start of Something Good,2718.0,NaN,87.0,"Drama, Romance",tt2331062,2012,English,6922161.00
14,Yannick has to deal with the haunting by himse...,True Storys of the Ghost House 3 the Demon Phe...,2718.0,NaN,87.0,Horror,tt3098520,2012,English,6922161.00
15,Seduced by the haunting beauty of a remote mar...,White Wind,2718.0,NaN,87.0,"Drama, Mystery",tt2555620,2012,English,6922161.00
16,A psychotic Iraq War veteran teaches his young...,Thelema the Equinox Diaries,2718.0,NaN,87.0,"Drama, Thriller",tt2443106,2012,English,6922161.00
17,A politician receives a message that his mistr...,Home Minister,2718.0,NaN,87.0,Drama,tt2923826,2012,English,6922161.00
18,A plot to assassinate the Vice President takes...,Placebo Effect,1752.0,http://ia.media-imdb.com/images/M/MV5BMTU5Njg1...,52.0,"Crime, Mystery, Thriller",tt0163154,1998,English,2890000.00
19,Long on the Island is a psychological thriller...,Long on the Island,2718.0,NaN,87.0,"Fantasy, Horror",tt2375263,2012,English,6922161.00
20,"Over the course of a single night, Dave and An...",I Did,2718.0,NaN,87.0,"Drama, Family",tt2388672,2012,English,6922161.00
21,"""Collaging Film"" is a series of shorts dating ...",Collaging Film,2718.0,NaN,87.0,Animation,tt4416372,2012,English,6922161.00
22,Hank lives the quiet life until a mysterious i...,Welcoming Departure,2718.0,http://ia.media-imdb.com/images/M/MV5BMjE0OTU2...,87.0,"Comedy, Drama",tt2235809,2012,English,6922161.00
23,The Luckiest Girl on the Lower East Side takes...,The Luckiest Girl on the Lower East Side,2718.0,NaN,87.0,Drama,tt1876494,2012,English,6922161.00
24,"Less Lost, is the fictional story of a young m...",Less Lost,1114.0,http://ia.media-imdb.com/images/M/MV5BMTk3MTg2...,68.0,"Drama, War",tt2259946,2012,English,1094116.00
25,High school student Aidan loses his girlfriend...,Still Here,2302.0,NaN,53.0,Drama,tt2275650,2012,English,5058001.00
26,Best friends Sam and Mike go out on a bender a...,The Hedgehog Dilemma,2718.0,http://ia.media-imdb.com/images/M/MV5BMTU1NDI3...,87.0,"Drama, Romance",tt2505274,2012,English,6922161.00
27,Filmed and produced by Australian director Sha...,51 Paintings,2457.0,http://ia.media-imdb.com/images/M/MV5BMTQyNzU2...,61.0,Drama,tt2318982,2012,English,5740816.00
28,"Capitalists, revolutionaries, and the people w...",The Adventures of Paul and Marian,2718.0,NaN,87.0,"Comedy, Musical, Romance",tt1949593,2012,English,6922161.00
29,Various people who lost loved ones during 9-11...,Above the Fire,2718.0,http://ia.media-imdb.com/images/M/MV5BMTUzNzc5...,87.0,Drama,tt2231544,2012,English,6922161.00
...,...,...,...,...,...,...,...,...,...,...
3359,Prabhavati lives a wealthy lifestyle in India ...,Sneham Kosam,NaN,NaN,6.3,"Family, Action",tt0246240,1999,Telugu,NaN
3360,The story of the famous Saint-Poet Manjunatha.,Sri Manjunatha,NaN,NaN,6.7,"Drama, Family, History, Musical",tt0249783,2001,Telugu,NaN
3361,Lord Rama's life is one of perfect adherence t...,Sri Rama Rajyam,635.0,NaN,7.2,Drama,tt1783377,2011,Telugu,394132.84
3362,Based on the life story of the great devotee-m...,Sri Ramadasu,207.0,NaN,6.9,"Biography, Musical",tt0459205,2006,Telugu,40040.01
3363,Josef Stalin rises from his rejection as being...,Stalin,653.0,http://ia.media-imdb.com/images/M/MV5BMTk5OTQw...,5.6,"Action, Drama",tt0105462,2006,Telugu,419126.76
3364,"The story of aspiring police officer, Prithvir...",State Rowdy,68.0,NaN,7.4,"Action, Crime, Drama",tt0246254,1989,Telugu,3672.36
3365,Aditya lives a middle-classed lifestyle in Aur...,Student No 1,473.0,NaN,6.7,"Action, Crime, Drama",tt1283956,2001,Telugu,217435.69
3366,Bantu and Chantu are two close friends and fel...,Style,NaN,NaN,5.8,Musical,tt0306855,2006,Telugu,NaN
3367,Amarchandra lives a poor lifestyle in British ...,Subhash Chandra Bose,NaN,NaN,2.9,"Action, Drama, History, Romance, Thriller",tt0459554,2005,Telugu,NaN
3368,Frank Darrbo is a hapless fry cook. When his w...,Super,NaN,http://ia.media-imdb.com/images/M/MV5BMTcxMDkx...,5.1,"Action, Comedy, Drama, Mystery, Romance",tt1512235,2005,Telugu,NaN
3369,Unable to convince the ruling council of Krypt...,Superman,49.0,http://ia.media-imdb.com/images/M/MV5BMTI1MjA5...,4.2,"Fantasy, Musical, Sci-Fi",tt0078346,1980,Telugu,2007.04
3370,A priceless idol is stolen from a temple trave...,Swamy Ra Ra,443.0,NaN,7.5,Crime,tt2767354,2013,Telugu,189660.25
3371,"The story of a classical singer, who finds it ...",Swathi Kiranam,NaN,NaN,7.8,"Family, Musical, Drama",tt0250012,1992,Telugu,NaN
3372,"Ravindranath Tagore, A physics professor forms...",Tagore,861.0,NaN,7.6,"Action, Drama",tt0361037,2003,Telugu,728291.56
3373,"Raja is a small-time outlaw, whose daring anti...",Takkari Donga,644.0,NaN,6.9,"Action, Adventure, Western",tt0307541,2002,Telugu,405896.41
3374,The story of an Indian Freedom fighter who fou...,Tandra Paparayudu,61.0,NaN,8.0,"Action, Biography, Drama, History",tt0253784,1986,Telugu,2809.00
3375,"Raghu, a business tycoon, is driving through a...",Tarzan Sundari,7.0,NaN,6.0,"Action, Adventure, Fantasy, Musical",tt2735328,1983,Telugu,1.00
3376,A man reconsiders his ideas about love in the ...,Teen Maar,909.0,NaN,5.8,"Comedy, Drama, Romance",tt1889440,2011,Telugu,815770.24
3377,Daya (NTR) is a fully corrupted police officer...,Temper,1331.0,NaN,8.1,"Action, Drama",tt4442758,2015,Telugu,1750064.41
3378,Classic about the life story of Carnatic Music...,Thyagayya,NaN,NaN,7.3,"Family, History, Musical",tt0246277,1946,Telugu,NaN
3379,"A romantic entertainer between a ""bava"" and a ...",Uyyala Jampala,NaN,NaN,7.5,"Drama, Family, Romance",tt3290676,2013,Telugu,NaN
3380,About to re-locate to the U.S. but refusing to...,Varudu,438.0,NaN,3.5,"Action, Crime, Drama, Thriller",tt1582637,2010,Telugu,188790.25
3381,Cable Raju is a slum dweller who works as a ca...,Vedam,2015.0,NaN,8.1,Drama,tt1649431,2010,Telugu,4027647.61
3382,A simple train journey to Tirupathi goes horri...,Venkatadri Express,79.0,NaN,7.5,"Adventure, Comedy",tt3573040,2013,Telugu,5112.25
3383,Venky and his friends are accused of murdering...,Venky,NaN,NaN,7.1,"Mystery, Romance",tt0417229,2004,Telugu,NaN
3384,"Vikram Rathod, A sincere Police man joins with...",Vikramarkudu,1158.0,NaN,7.5,"Action, Comedy, Crime, Thriller",tt0858492,2006,Telugu,1323650.25
3385,After an eventful train trip on the Visakha/Ra...,Visakha Express,43.0,NaN,4.5,"Crime, Drama, Mystery, Thriller",tt1285147,2008,Telugu,1482.25
3386,"Mahi is a beautiful wealthy heiress, but her f...",Yamadonga,1316.0,NaN,7.3,"Action, Comedy, Fantasy, Romance",tt0924317,2007,Telugu,1712695.69
3387,Yevade Subramanyam has wrapped its shooting an...,Yevade Subramanyam,188.0,NaN,7.9,"Adventure, Comedy, Drama",tt4515070,2015,Telugu,32436.01
3388,Sathya (Allu Arjun) returns from a coma to tak...,Yevadu,3966.0,NaN,4.6,"Action, Thriller",tt2211173,2014,Telugu,15692689.96